# Generated by Django 5.1.15 on 2026-09-11 18:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_number', models.CharField(db_index=True, max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('narration', models.TextField()),
                ('status', models.CharField(default='POSTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'journal_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
            ],
            options={
                'db_table': 'journal_lines',
            },
        ),
        migrations.CreateModel(
            name='AccountHead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity / Share Capital'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_accounts', to='accounting.accounthead')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_heads', to='tenants.tenant')),
            ],
            options={
                'db_table': 'account_heads',
                'ordering': ['code'],
            },
        ),
    ]
