# Generated by Django 5.1.15 on 2026-09-11 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='account_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.accounthead'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_lines', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='accounthead',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('tenant', 'entry_number')},
        ),
    ]
