# Generated by Django 5.1.15 on 2026-09-11 18:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('meeting_date', models.DateField()),
                ('agenda', models.TextField()),
                ('minutes', models.TextField(blank=True, default='')),
                ('resolutions', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'committee_meetings',
                'ordering': ['-meeting_date'],
            },
        ),
    ]
