# Generated by Django 5.1.15 on 2026-09-11 18:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(db_index=True, max_length=50)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('interest_rate_pa', models.DecimalField(decimal_places=2, default=4.0, max_digits=5)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('opened_date', models.DateField(auto_now_add=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='savings_account', to='members.member')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_accounts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'savings_accounts',
                'unique_together': {('tenant', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Cash / Bank Deposit'), ('WITHDRAWAL', 'Cash / Bank Withdrawal'), ('INTEREST_CREDIT', 'Interest Credit')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_transactions', to='tenants.tenant')),
                ('savings_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='deposits.savingsaccount')),
            ],
            options={
                'db_table': 'deposit_transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='TermDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deposit_number', models.CharField(db_index=True, max_length=50)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_rate_pa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tenure_months', models.IntegerField(default=12)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('maturity_date', models.DateField()),
                ('maturity_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_deposits', to='members.member')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_deposits', to='tenants.tenant')),
            ],
            options={
                'db_table': 'term_deposits',
                'ordering': ['-start_date'],
                'unique_together': {('tenant', 'deposit_number')},
            },
        ),
    ]
