# Generated by Django 5.1.15 on 2026-09-30 10:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('tenants', '0004_alter_subscription_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_index', models.PositiveIntegerField(db_index=True)),
                ('previous_hash', models.CharField(max_length=64)),
                ('merkle_root', models.CharField(max_length=64)),
                ('block_hash', models.CharField(db_index=True, max_length=64)),
                ('nonce', models.PositiveBigIntegerField(default=0)),
                ('difficulty', models.PositiveSmallIntegerField(default=2)),
                ('tx_count', models.PositiveIntegerField(default=0)),
                ('is_anchored', models.BooleanField(default=False)),
                ('anchor_network', models.CharField(default='Polygon PoS', max_length=50)),
                ('anchor_tx_hash', models.CharField(blank=True, default='', max_length=100)),
                ('anchor_timestamp', models.DateTimeField(blank=True, null=True)),
                ('sealed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_blocks', to='tenants.tenant')),
            ],
            options={
                'db_table': 'blockchain_blocks',
                'ordering': ['-block_index'],
                'unique_together': {('tenant', 'block_index')},
            },
        ),
        migrations.CreateModel(
            name='BlockTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_index', models.PositiveIntegerField(default=0)),
                ('tx_hash', models.CharField(db_index=True, max_length=64)),
                ('tx_type', models.CharField(db_index=True, max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('payload', models.JSONField(default=dict)),
                ('merkle_proof', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_transactions', to=settings.AUTH_USER_MODEL)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='audit.blockchainblock')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_transactions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'block_transactions',
                'ordering': ['created_at'],
            },
        ),
    ]
