# Generated by Django 5.1.15 on 2026-09-11 18:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.CharField(db_index=True, max_length=50)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_VERIFICATION', 'Under Verification'), ('UNDER_ASSESSMENT', 'Under Assessment'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SANCTIONED', 'Sanctioned'), ('DISBURSED', 'Disbursed'), ('CLOSED', 'Closed')], db_index=True, default='SUBMITTED', max_length=30)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='members.member')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='tenants.tenant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loan_applications',
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(db_index=True, max_length=50)),
                ('sanctioned_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('disbursed_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('disbursed_date', models.DateTimeField(auto_now_add=True)),
                ('interest_rate_pa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('outstanding_principal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('outstanding_interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('overdue_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('loan_status', models.CharField(choices=[('CURRENT', 'Current'), ('DUE', 'Due Soon'), ('OVERDUE', 'Overdue'), ('PARTIALLY_PAID', 'Partially Paid'), ('RECOVERY', 'Under Recovery'), ('CLOSED', 'Closed')], db_index=True, default='CURRENT', max_length=20)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_accounts', to='members.member')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_accounts', to='tenants.tenant')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan_account', to='loans.loanapplication')),
            ],
            options={
                'db_table': 'loan_accounts',
                'ordering': ['-disbursed_date'],
                'unique_together': {('tenant', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('interest_rate_pa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_amount', models.DecimalField(decimal_places=2, default=1000.0, max_digits=18)),
                ('max_amount', models.DecimalField(decimal_places=2, default=500000.0, max_digits=18)),
                ('tenure_months', models.IntegerField(default=12)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_products', to='tenants.tenant')),
            ],
            options={
                'db_table': 'loan_products',
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='loans.loanproduct'),
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=18)),
                ('principal_component', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_component', models.DecimalField(decimal_places=2, max_digits=18)),
                ('penalty_component', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('payment_mode', models.CharField(default='CASH', max_length=30)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loanaccount')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='members.member')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_repayments', to='tenants.tenant')),
            ],
            options={
                'db_table': 'loan_repayments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='loanapplication',
            unique_together={('tenant', 'application_number')},
        ),
    ]
