# Generated by Django 5.1.15 on 2026-09-19 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        ('members', '0004_member_kyc_method_member_kyc_rejection_reason_and_more'),
        ('tenants', '0002_alter_tenant_contact_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRepaymentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('principal_due', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_due', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=18)),
                ('principal_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('interest_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('penalty_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], db_index=True, default='PENDING', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loan_repayment_schedules',
                'ordering': ['installment_number'],
            },
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='excess_credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='excess_component',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddConstraint(
            model_name='loanaccount',
            constraint=models.CheckConstraint(condition=models.Q(('outstanding_principal__gte', 0)), name='chk_loan_principal_pos'),
        ),
        migrations.AddConstraint(
            model_name='loanaccount',
            constraint=models.CheckConstraint(condition=models.Q(('outstanding_interest__gte', 0)), name='chk_loan_interest_pos'),
        ),
        migrations.AddConstraint(
            model_name='loanaccount',
            constraint=models.CheckConstraint(condition=models.Q(('excess_credit__gte', 0)), name='chk_loan_excess_pos'),
        ),
        migrations.AddConstraint(
            model_name='loanproduct',
            constraint=models.CheckConstraint(condition=models.Q(('interest_rate_pa__gte', 0), ('interest_rate_pa__lte', 100)), name='chk_loan_interest_rate_range'),
        ),
        migrations.AddConstraint(
            model_name='loanproduct',
            constraint=models.CheckConstraint(condition=models.Q(('min_amount__gte', 0)), name='chk_loan_min_amt'),
        ),
        migrations.AddConstraint(
            model_name='loanrepayment',
            constraint=models.CheckConstraint(condition=models.Q(('total_paid__gt', 0)), name='chk_repayment_positive'),
        ),
        migrations.AddField(
            model_name='loanrepaymentschedule',
            name='loan_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='loans.loanaccount'),
        ),
        migrations.AddField(
            model_name='loanrepaymentschedule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_schedules', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='loanrepaymentschedule',
            unique_together={('loan_account', 'installment_number')},
        ),
    ]
