# Generated by Django 5.1.15 on 2026-09-29 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanrepaymentschedule_loanaccount_excess_credit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanproduct',
            options={'ordering': ['-created_at']},
        ),
    ]
