# Generated by Django 5.1.15 on 2026-09-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpdevice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='otpdevice',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otpdevice',
            name='max_attempts',
            field=models.IntegerField(default=3),
        ),
    ]
