# Generated by Django 5.1.15 on 2026-09-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otpdevice_options_otpdevice_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpdevice',
            name='code_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpdevice',
            name='code',
            field=models.CharField(max_length=64),
        ),
    ]
