# Generated by Django 5.1.15 on 2026-09-11 18:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_number', models.CharField(db_index=True, max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('village', models.CharField(db_index=True, max_length=100)),
                ('taluk', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(default='Karnataka', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('CLOSED', 'Membership Closed')], db_index=True, default='ACTIVE', max_length=20)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tenants.tenant')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'members',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'member_number')},
            },
        ),
        migrations.CreateModel(
            name='MemberAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='members.member')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_assets', to='tenants.tenant')),
            ],
            options={
                'db_table': 'member_assets',
            },
        ),
        migrations.CreateModel(
            name='MemberFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, default='', max_length=100)),
                ('is_dependent', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='members.member')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_families', to='tenants.tenant')),
            ],
            options={
                'db_table': 'member_family',
            },
        ),
        migrations.CreateModel(
            name='MemberLand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('survey_number', models.CharField(db_index=True, max_length=100)),
                ('area_acres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='Acres', max_length=20)),
                ('village', models.CharField(max_length=100)),
                ('taluk', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('ownership_type', models.CharField(default='Self Owned', max_length=50)),
                ('land_status', models.CharField(default='REGISTERED', max_length=30)),
                ('registered_date', models.DateField(auto_now_add=True)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='members.member')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_lands', to='tenants.tenant')),
            ],
            options={
                'db_table': 'member_lands',
            },
        ),
    ]
