# Generated by Django 5.1.15 on 2026-09-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='aadhaar_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='member',
            name='blood_group',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='board_resolution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='board_resolution_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='caste_category',
            field=models.CharField(blank=True, default='OBC', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='dccb_sb_account_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='is_kyc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='ledger_folio_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='local_language_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, default='Single', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='occupation',
            field=models.CharField(blank=True, default='Agriculture', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='religion',
            field=models.CharField(blank=True, default='Hinduism', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
