# Generated by Django 5.1.15 on 2026-09-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_kyc_method_member_kyc_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='blood_group',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='board_resolution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='board_resolution_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='caste_category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='dccb_sb_account_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='land_crop_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='land_irrigation_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='land_ownership_type',
            field=models.CharField(default='Self Owned', max_length=50),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='land_rtc_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='land_unit',
            field=models.CharField(default='Acres', max_length=20),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='ledger_folio_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='local_language_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='marital_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='religion',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='spouse_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
