# Generated by Django 5.1.15 on 2026-09-11 18:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('village', models.CharField(blank=True, default='', max_length=100)),
                ('taluk', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(default='Karnataka', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('dccb_name', models.CharField(blank=True, default='', help_text='District Central Cooperative Bank', max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('subscription_plan', models.CharField(default='STANDARD', max_length=50)),
                ('subscription_start', models.DateField(blank=True, null=True)),
                ('subscription_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['-created_at'],
            },
        ),
    ]
