# Generated by Django 5.1.15 on 2026-09-26 06:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_contact_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tenant',
            name='society_type',
            field=models.CharField(choices=[('PACS', 'Primary Agricultural Credit Society (PACS)'), ('AGRICULTURAL', 'Agricultural Cooperative Society'), ('CREDIT', 'Credit Cooperative Society'), ('MULTIPURPOSE', 'Multipurpose Cooperative Society'), ('OTHER', 'Other')], default='PACS', max_length=30),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='code',
            field=models.CharField(db_index=True, help_text='Unique tenant code e.g. PKPS-MANDYA-0001', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='registration_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('DOCUMENTS_PENDING', 'Documents Pending'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subscription_plan',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('BASIC', 'Basic'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='TRIAL', max_length=20),
        ),
        migrations.CreateModel(
            name='SocietyAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=255)),
                ('village_town', models.CharField(max_length=100)),
                ('gram_panchayat', models.CharField(blank=True, default='', max_length=100)),
                ('taluk', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(default='Karnataka', max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('official_mobile', models.CharField(blank=True, default='', max_length=20)),
                ('official_email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registered_address', to='tenants.tenant')),
            ],
            options={
                'db_table': 'society_addresses',
            },
        ),
        migrations.CreateModel(
            name='SocietyAuthorizedPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('id_type', models.CharField(blank=True, default='', help_text='e.g. Aadhaar, PAN, Passport', max_length=50)),
                ('id_number', models.CharField(blank=True, default='', max_length=50)),
                ('authorization_document', models.FileField(blank=True, null=True, upload_to='auth_documents/%Y/%m/')),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_persons', to='tenants.tenant')),
            ],
            options={
                'db_table': 'society_authorized_persons',
            },
        ),
        migrations.CreateModel(
            name='SocietyBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_type', models.CharField(choices=[('DCCB', 'District Central Cooperative Bank (DCCB)'), ('STCB', 'State Cooperative Bank (StCB)'), ('NATIONALIZED', 'Nationalized Bank'), ('PRIVATE', 'Private Bank'), ('RRB', 'Regional Rural Bank (RRB)'), ('OTHER', 'Other')], default='DCCB', max_length=20)),
                ('bank_name', models.CharField(max_length=200)),
                ('branch_name', models.CharField(blank=True, default='', max_length=200)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=20)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings Account'), ('CURRENT', 'Current Account'), ('OVERDRAFT', 'Overdraft Account'), ('LOAN', 'Loan Account'), ('OTHER', 'Other')], default='CURRENT', max_length=20)),
                ('account_holder_name', models.CharField(blank=True, default='', max_length=255)),
                ('dccb_customer_id', models.CharField(blank=True, default='', max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'society_bank_accounts',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocietyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('REGISTRATION_CERTIFICATE', 'Registration Certificate'), ('BYE_LAWS', 'Bye-Laws'), ('MEMORANDUM', 'Memorandum / Formation Document'), ('PAN', 'PAN'), ('ADDRESS_PROOF', 'Registered Office Address Proof'), ('BOARD_RESOLUTION', 'Board/Committee Resolution'), ('SIGNATORY_ID', 'Authorized Signatory ID Proof'), ('AUDIT_REPORT', 'Latest Audit Report'), ('OTHER', 'Other')], max_length=30)),
                ('document_name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='society_documents/%Y/%m/')),
                ('file_url', models.CharField(blank=True, default='', max_length=500)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_documents', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='society_uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='society_verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'society_documents',
                'ordering': ['document_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocietyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=100)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('registration_authority', models.CharField(blank=True, default='Registrar of Cooperative Societies', max_length=200)),
                ('society_category', models.CharField(blank=True, default='', max_length=100)),
                ('pan', models.CharField(blank=True, default='', help_text='PAN Number', max_length=15)),
                ('certificate_number', models.CharField(blank=True, default='', max_length=100)),
                ('area_of_operation', models.CharField(choices=[('VILLAGE', 'Village'), ('MULTIPLE_VILLAGES', 'Multiple Villages'), ('GRAM_PANCHAYAT', 'Gram Panchayat'), ('TALUK', 'Taluk'), ('DISTRICT', 'District'), ('OTHER', 'Other')], default='VILLAGE', max_length=30)),
                ('operation_villages', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='tenants.tenant')),
            ],
            options={
                'db_table': 'society_profiles',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('TRIAL', 'Trial'), ('BASIC', 'Basic'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='TRIAL', max_length=20)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('member_limit', models.IntegerField(default=500)),
                ('staff_limit', models.IntegerField(default=10)),
                ('storage_limit_mb', models.IntegerField(default=1024)),
                ('branch_limit', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='TenantInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('invited_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
