# Generated by Django 5.1.15 on 2026-09-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_logo_url_tenant_society_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='TRIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subscription_plan',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='TRIAL', max_length=20),
        ),
    ]
