# Generated by Django 5.1.15 on 2026-09-11 18:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financial_year', models.CharField(max_length=20)),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('dividend_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dividend_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('DECLARED', 'Declared'), ('PAID', 'Paid / Transferred')], default='DECLARED', max_length=20)),
                ('declared_date', models.DateField(auto_now_add=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='members.member')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividend_records', to='tenants.tenant')),
            ],
            options={
                'db_table': 'dividend_records',
                'ordering': ['-declared_date'],
            },
        ),
        migrations.CreateModel(
            name='ShareAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_shares', models.PositiveIntegerField(default=0)),
                ('share_unit_price', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_account', to='members.member')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_accounts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'share_accounts',
            },
        ),
        migrations.CreateModel(
            name='ShareTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Share Purchase / Deposit'), ('WITHDRAWAL', 'Share Refund / Redemption')], max_length=20)),
                ('number_of_shares', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('share_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='shares.shareaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_transactions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'share_transactions',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
