# Generated by Django 5.1.15 on 2026-09-29 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shareaccount',
            options={'ordering': ['-created_at']},
        ),
    ]
